[package]
name = "crawler"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
libc = "0.2.182" 
arrow = { version = "58.0.0", features = ["ffi", "csv"] }
arrow-array = "58.0.0"
arrow-schema = "58.0.0"

[build-dependencies]
cbindgen = "0.29.2" # Add build dependencies for cbindgen
